### ISSUE TITLE
CI failure with Swift 5

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/KituraKit#45]
#42 aims to add Swift 5 testing to the CI, but one of the tests fails on Linux with:

`/home/travis/build/IBM-Swift/KituraKit/Tests/KituraKitTests/BasicAuthTests.swift:90: error: BasicAuthTests.testBasicAuthUnauthorized : XCTAssertEqual failed: ("601 : A connection error occurred, cannot connect to the server. Please ensure that the server is started and running, with the correct port and URL ('ToDoServer' if using the sample app).") is not equal to ("401 : Unauthorized") - `
`Fatal error: Trying to remove task, but it's not in the registry.: file /home/buildnode/jenkins/workspace/oss-swift-5.0-package-linux-ubuntu-16_04/swift-corelibs-foundation/Foundation/URLSession/TaskRegistry.swift, line 76`
`/home/travis/build/IBM-Swift/KituraKit/Tests/KituraKitTests/BasicAuthTests.swift:91: error: BasicAuthTests.testBasicAuthUnauthorized : API violation - multiple calls made to XCTestExpectation.fulfill() for A response is received from the server -> .unauthorized.`
`Exited with signal code 4`

This needs investigation.

**Comment by Andrew-Lees11** [comment]
I created a gist that would recreate the test failure [here](https://gist.github.com/Andrew-Lees11/a23d37c3ab81aa8ad17125b3766ad601).

When a Kitura server returns a 401 unauthorized code the callback on URLSession.dataTask is called twice. once with "The operation could not be completed" and then with the response from Kitura. This is not true for other error codes and only happens on Swift 5 on Linux.

I think [This Stackoverflow error](https://stackoverflow.com/questions/54621070/urlerror-nserror-the-operation-could-not-be-completed-error-when-trying-to-st) May be running into the same problem since it is only failing on Linux but i'm not entirely sure.

**Comment by saiHemak** [comment]
Could successfully recreate the issue from TestFoundation. Upon instrumenting the code I could see the ```urlsession.remove``` is getting called twice . Instrumenting further to identify why the ```remove``` call has been triggered twice ..

**Comment by pushkarnk** [comment]
@saiHemak this seems to be reported over Twitter too https://twitter.com/mxcl/status/1111073495017029635

**Comment by saiHemak** [comment]
``` session.taskRegistry.remove(task)``` has been called twice once from ```urlProtocol(`protocol`, didFailWithError: urlError)``` and the from the switch case ```case .dataCompletionHandler(let completion):```

**Comment by saiHemak** [comment]
created PR https://github.com/apple/swift-corelibs-foundation/pull/2061

**Comment by ianpartridge** [comment]
Please open an issue to track re-enabling these tests once Swift 5.0.1 ships with the fix.

**Comment by Andrew-Lees11** [comment]
Raised an issue to uncomment the tests [here](https://github.com/IBM-Swift/KituraKit/issues/47)
